name: Build and Deploy AMD64 Architecture

on:
  push:
    branches:
      - master

env:
  GAR_REGION: ${{ secrets.GAR_REGION }}
  GCR_SERVICE_AMD: ${{ secrets.GCR_SERVICE_AMD }}
  GAR_NAME_AMD: ${{ secrets.GAR_NAME_AMD }}
  GAR_REPO_NAME_AMD: ${{ secrets.GAR_REPO_NAME_AMD }}

jobs:
  build-and-deploy-amd64:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Configure Docker for GAR
      - name: Configure Docker Auth for GAR
        run: |
          gcloud auth configure-docker ${{ env.GAR_REGION }}-docker.pkg.dev

      # Step 5: Set up QEMU for Multi-Architecture Builds
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      # Step 6: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 7: Build and Push AMD64 Image
      - name: Build and Push AMD64 Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ${{ env.GAR_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.GAR_REPO_NAME_AMD }}/${{ env.GAR_NAME_AMD }}:${{ github.sha }} .

      # Step 8: Deploy AMD64 Image to Cloud Run
      - name: Deploy AMD64 to Cloud Run
        run: |
          gcloud run deploy ${{ env.GCR_SERVICE_AMD }} \
            --image ${{ env.GAR_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.GAR_REPO_NAME_AMD }}/${{ env.GAR_NAME_AMD }}:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.GCR_REGION }} \
            --port 8349 \
            --allow-unauthenticated

      # Step 9: Summary
      - name: Show AMD64 Deployment URL
        run: |
          echo "AMD64 Deployment URL: https://${{ env.GCR_SERVICE_AMD }}-${{ secrets.GCP_REGION }}.a.run.app"
